### ISSUE TITLE
About the Census data

### ISSUE THREAD

**Issue by dreamzzzz5** [gsagostini/networks_underreporting#1]
Hi, I would like to ask how to obtain Census 2020 tables P1, P9, P10, P13, H4 as well as ACS 2020 5-year estimates S1901, B15003, B25003.

**Comment by gsagostini** [comment]
Hi @dreamzzzz5 you can filter for the corresponding surveys and tables on the advanced search feature of the Census data website: https://data.census.gov/advanced
